## My Feature selection and Model Selection

In [56]:
import pandas as pd
import numpy as np

In [57]:
df = pd.read_csv("data/ready_to_process.csv", sep = ',', header = 'infer')
df.head(1)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,num_critic_for_reviews,director_facebook_likes,actor_1_name,actor_1_facebook_likes,actor_2_name,actor_2_facebook_likes,actor_3_name,actor_3_facebook_likes,num_user_for_reviews,movie_facebook_likes
0,1.0,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000.0,['Comedy'],NaN,tt2637294,en,Hot Tub Time Machine 2,When Lou who has become the father of the Inte...,6.575393,...,107.0,38.0,Adam Scott,3000.0,Gillian Jacobs,837.0,Collette Wolfe,390.0,96.0,0

In [58]:
df.shape

(5305, 41)

In [59]:
df.columns.tolist()

['id',
 'belongs_to_collection',
 'budget',
 'genres',
 'homepage',
 'imdb_id',
 'original_language',
 'original_title',
 'overview',
 'popularity',
 'poster_path',
 'production_companies',
 'production_countries',
 'release_date',
 'runtime',
 'spoken_languages',
 'status',
 'tagline',
 'title',
 'Keywords',
 'cast',
 'crew',
 'revenue',
 'tconst',
 'averageRating',
 'release_year',
 'release_month',
 'release_day',
 'budget_adjusted',
 'budget_adjusted_log',
 'director_name',
 'num_critic_for_reviews',
 'director_facebook_likes',
 'actor_1_name',
 'actor_1_facebook_likes',
 'actor_2_name',
 'actor_2_facebook_likes',
 'actor_3_name',
 'actor_3_facebook_likes',
 'num_user_for_reviews',
 'movie_facebook_likes']

## Feature selection

In [60]:
df1 = df.copy()

In [61]:
# make movie_title an index of df1
df1 = df1.set_index("original_title")

In [62]:
# separate Y label
Y = df1["averageRating"]

## Since, there still have many features that is not important. 
- Hence, I will doing the feature cutting and drop pitfull issue

In [63]:
df1.head(1)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,overview,popularity,poster_path,...,num_critic_for_reviews,director_facebook_likes,actor_1_name,actor_1_facebook_likes,actor_2_name,actor_2_facebook_likes,actor_3_name,actor_3_facebook_likes,num_user_for_reviews,movie_facebook_likes
original_title,,,,,,,,,,,,,,,,,,,,,
Hot Tub Time Machine 2,1.0,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000.0,['Comedy'],NaN,tt2637294,en,When Lou who has become the father of the Inte...,6.575393,/tQtWuwvMf0hCc2QR2tkolwl7c3c.jpg,...,107.0,38.0,Adam Scott,3000.0,Gillian Jacobs,837.0,Collette Wolfe,390.0,96.0,0

In [64]:
df1['budget_adjusted']

original_title
Hot Tub Time Machine 2                      1.833018e+07
The Princess Diaries 2: Royal Engagement    6.355883e+07
Whiplash                                    4.325814e+06
The Possession                              1.892281e+07
The Possession                              1.892281e+07
                                                ...
NaN                                                  NaN
NaN                                                  NaN
NaN                                                  NaN
NaN                                                  NaN
NaN                                                  NaN
Name: budget_adjusted, Length: 5305, dtype: float64

In [65]:
# I need the budget_adj for convert 
new_df = df[['imdb_id', 'budget_adjusted']]

In [66]:
new_df.to_csv('data/imdb_budget.csv', index=False)

In [67]:
ready = pd.read_csv('data/ready_to_process_v02.csv')

## Remove some not important features

![feature vs rating](data/feature_importance_updated.png)

In [22]:
df1.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'overview', 'popularity', 'poster_path',
       'production_companies', 'production_countries', 'release_date',
       'runtime', 'spoken_languages', 'status', 'tagline', 'title', 'Keywords',
       'cast', 'crew', 'revenue', 'tconst', 'averageRating', 'release_year',
       'release_month', 'release_day', 'budget_adjusted',
       'budget_adjusted_log', 'director_name', 'num_critic_for_reviews',
       'director_facebook_likes', 'actor_1_name', 'actor_1_facebook_likes',
       'actor_2_name', 'actor_2_facebook_likes', 'actor_3_name',
       'actor_3_facebook_likes', 'num_user_for_reviews',
       'movie_facebook_likes'],
      dtype='object')

In [23]:
remove = [ "id" ,"belongs_to_collection", "homepage",  "budget", "imdb_id", "original_language", 
            "overview", "poster_path", "production_companies", "production_countries", "production_countries", 
          "revenue", "tconst", "release_day", "budget_adjusted","release_day", "cast", "crew"
         ]

In [24]:
# the remaining dataframe (note: not all left are predictive features yet)
df1 = df1.drop(remove, axis = 1)

In [25]:
df1.head(1)

,genres,popularity,release_date,runtime,spoken_languages,status,tagline,title,Keywords,averageRating,...,num_critic_for_reviews,director_facebook_likes,actor_1_name,actor_1_facebook_likes,actor_2_name,actor_2_facebook_likes,actor_3_name,actor_3_facebook_likes,num_user_for_reviews,movie_facebook_likes
original_title,,,,,,,,,,,,,,,,,,,,,
Hot Tub Time Machine 2,['Comedy'],6.575393,2015-02-20,93.0,['English'],Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...",5.0,...,107.0,38.0,Adam Scott,3000.0,Gillian Jacobs,837.0,Collette Wolfe,390.0,96.0,0

In [26]:
df1.columns

Index(['genres', 'popularity', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'averageRating',
       'release_year', 'release_month', 'budget_adjusted_log', 'director_name',
       'num_critic_for_reviews', 'director_facebook_likes', 'actor_1_name',
       'actor_1_facebook_likes', 'actor_2_name', 'actor_2_facebook_likes',
       'actor_3_name', 'actor_3_facebook_likes', 'num_user_for_reviews',
       'movie_facebook_likes'],
      dtype='object')

In [27]:
remove2 = [ "release_date", "spoken_languages", "status", "tagline", "title", "Keywords", "director_name",
           "actor_1_name", "actor_2_name", "actor_3_name"
         ]

In [28]:
# the remaining dataframe (note: not all left are predictive features yet)
df1 = df1.drop(remove2, axis = 1)

### Why do we remove these features?

ID, IMDb ID, tconst: These are unique identifiers and do not provide any predictive value for the model.

Belongs to Collection, Homepage, Poster Path: These are metadata or links related to marketing or UI display, not useful for modeling.

Original Language: Since we're only focusing on English-language movies, this column has no variance and adds no value.

Overview, Tagline, Title, Keywords: These are textual features. While potentially useful with NLP techniques, they require complex preprocessing and are excluded in this version for simplicity.

Budget, Budget Adjusted, Revenue: These features are often missing or inaccurately reported. To avoid introducing noise or relying on unreliable data, we remove them here.

Release Date, Release Day, Status, Spoken Languages: Either redundant, too granular (day vs. date), or non-informative for rating prediction.

Production Companies, Production Countries: These involve many unique values, which could lead to high-cardinality categorical variables. We exclude them to simplify the model.

Cast, Crew: These are complex nested JSON-like structures. Instead, we extract and process only key members (e.g., top actors or director) separately if needed.

Director Name, Actor1, 2, and 3 Name: Names are high-cardinality features and not directly useful unless we extract meaningful numerical or categorical representations (like Facebook likes or prior success). For this model, we exclude raw name fields.

In [30]:
df1.head(5)

,genres,popularity,runtime,averageRating,release_year,release_month,budget_adjusted_log,num_critic_for_reviews,director_facebook_likes,actor_1_facebook_likes,actor_2_facebook_likes,actor_3_facebook_likes,num_user_for_reviews,movie_facebook_likes
original_title,,,,,,,,,,,,,,
Hot Tub Time Machine 2,['Comedy'],6.575393,93.0,5.0,2015.0,2.0,16.724059,107.0,38.0,3000.0,837.0,390.0,96.0,0
The Princess Diaries 2: Royal Engagement,"['Comedy', 'Drama', 'Family', 'Romance']",8.248895,113.0,5.9,2004.0,8.0,17.967477,77.0,0.0,11000.0,1000.0,995.0,152.0,1000
Whiplash,['Drama'],44.775274,105.0,8.5,2014.0,10.0,15.280111,535.0,141.0,24000.0,970.0,535.0,731.0,129000
The Possession,"['Horror', 'Thriller']",7.286477,92.0,5.9,2012.0,8.0,16.755879,264.0,30.0,941.0,459.0,309.0,162.0,17000
The Possession,"['Horror', 'Thriller']",7.286477,92.0,5.9,2012.0,8.0,16.755879,264.0,30.0,941.0,459.0,309.0,162.0,17000

## Since, the generes has many subset infors. I will only collection the first one
- i.e if geres = ['Comedy', 'Drama', 'Family', 'Romance'].
- I will only need first one comedy. Remove the reset of those
- After finished this genres clean. called "ready_to_process_v02"

In [32]:
check = pd.read_csv("data/ready_to_process_v02.csv", sep = ',', header = 'infer')
check.head(1)

,original_title,popularity,runtime,averageRating,release_year,release_month,budget_adjusted_log,num_critic_for_reviews,director_facebook_likes,actor_1_facebook_likes,actor_2_facebook_likes,actor_3_facebook_likes,num_user_for_reviews,movie_facebook_likes,Genre_first_values
0,Hot Tub Time Machine 2,6.575393,93.0,5.0,2015.0,2.0,16.724059,107.0,38.0,3000.0,837.0,390.0,96.0,0,Comedy

In [33]:
check.shape

(5305, 15)

In [34]:
check.head(5)

,original_title,popularity,runtime,averageRating,release_year,release_month,budget_adjusted_log,num_critic_for_reviews,director_facebook_likes,actor_1_facebook_likes,actor_2_facebook_likes,actor_3_facebook_likes,num_user_for_reviews,movie_facebook_likes,Genre_first_values
0,Hot Tub Time Machine 2,6.575393,93.0,5.0,2015.0,2.0,16.724059,107.0,38.0,3000.0,837.0,390.0,96.0,0,Comedy
1,The Princess Diaries 2: Royal Engagement,8.248895,113.0,5.9,2004.0,8.0,17.967477,77.0,0.0,11000.0,1000.0,995.0,152.0,1000,Comedy
2,Whiplash,44.775274,105.0,8.5,2014.0,10.0,15.280111,535.0,141.0,24000.0,970.0,535.0,731.0,129000,Drama
3,The Possession,7.286477,92.0,5.9,2012.0,8.0,16.755879,264.0,30.0,941.0,459.0,309.0,162.0,17000,Horror
4,The Possession,7.286477,92.0,5.9,2012.0,8.0,16.755879,264.0,30.0,941.0,459.0,309.0,162.0,17000,Horror

## Right now, I can training my model.